name: RealShop2
main: fr.crafter.tickleman.realshop2.RealShop2Plugin
version: 2.4
website: http://plugins.crafter.fr/tickleman/RealShop2/
author: tickleman
depend: [RealPlugin]
commands:
  mny:
    description: RealEconomy money commands
    usage: Use /mny help to list available commands
  realshop:
    aliases: [rs, rshop]
    description: RealShop2 chest-shop commands
    usage: Use /realshop help to list available commands
